<?php include("NavigationBar.php"); ?>


<!DOCTYPE html>
<html>
<div style="text-align: center;">
  <head>
    <title>Everybody Welcome</title>
  </head>
  <body>
    <h1>Everybody Welcome</h1>
    <p>There are one billion people in the world with additional access needs, including over 14 million disabled people in the U.K.</p>
    <p>93% will search for access information about your venue before they visit and, if they can’t find what they are looking for, 41% will take their business elsewhere meaning that you could be missing out on valuable custom just for the sake of providing relevant information*.</p>
    <p>(*Source: Euan’s Guide Access Survey 2019)</p>
    <p>But what information should you provide? How should you provide it, when should you promote it and where?</p>
    <p>Everybody Welcome is the easy way to share your accessibility information and welcome the world.</p>
    <p>So what are you waiting for? Start creating your listing now!</p>
    <p>(*Source: Euan’s Guide Access Survey 2019)</p>
    <h2>What is Everybody Welcome?</h2>
    <p>Everybody Welcome is a straightforward, smart tool to help you record, share and market relevant accessibility information about your venue.</p>
    <h2>Why is it needed?</h2>
    <p>Research shows that more than half of disabled people are not confident about visiting new places and that 79% have had a disappointing trip or had to change their plans at the last minute due to poor accessibility. 77% also find that accessibility information hard to find or inaccurate.* (*Source: Euan’s Guide Access Survey 2019)</p>
    <p>Venues, on the other hand, are unsure what information provide or find existing methods of providing access information costly, complicated or time-consuming so often provide nothing.</p>
    <p>As a result, people with additional access needs are missing out on visits and experiences and businesses are missing out on the additional income that would be generated by those visits.</p>
    <p>Everybody Welcome is designed to change that by supporting businesses to provide relevant accessibility information easily and quickly and enabling consumers to plan visits with ease.</p>
    <h2>What do I need to do?</h2>
    <p>Simply answer a short series of questions about your business, venue or service, add some images and in just a few clicks you have a handy, accurate accessibility summary that you can share on your website, in your social media or anywhere else that takes your fancy!</p>
    <h2>What do I get?</h2>
    <p>Not only does creating an Everybody Welcome listing give you a unique URL to share with your target audiences, it also generates an exclusive QR code to display around your venue, enabling you to provide access information for your visitors when and where they need it.</p>
    <p>Your Everybody Welcome listing also links back to your own website, ensuring that visitors who need additional information know exactly where to find it.</p>
    <p>Each listing is included in our free to use directory which enables potential visitors to search for venues by location, type or accessibility features, leading to better experiences for visitors and increased footfall and revenue for you.</p>
    <p>If you want to dig a little deeper, our Access Tracker self-audit tool will enable to you to audit the accessibility of your offering in more detail, providing information and tools to support you in creating an action plan for improvement.</p>
    <h2>How much does it cost?</h2>
    <p>Everybody Welcome is free to use and includes listing in the Directory for one year. At the end of each year,
    you will be prompted to check the accuracy of your listing before it renews, giving you the opportunity to
    make changes and giving visitors confidence that the information provided is current, relevant and
    accurate.</p>
    <p>For those who want to take their accessibility to the next level, our Access Tracker tool is available at just
    £XXXX per year.</p>
    <h2>What are the other advantages?</h2>
    <p>Destinations are now recognising the value of the Purple Pound: the spending power of disabled people,
    which is worth over £274billion in the U.K. alone. Creating Everybody Welcome guides within a given
    destination starts to improve the accessibility of the destination as a whole, increasing visitor numbers,
    enhancing revenue and improving visitor experiences.</p>
    <p>The U.K. government too has recognised the opportunity for growth that this sector has. In fact, the 2021
    Tourism Recovery Plan aims for the U.K. to be THE most accessible tourism destination in Europe by 2025
    and to increase the number of disabled visitors from Europe by one third by this time. Providing accurate
    accessibility information is key to achieving this goal and is exactly what Everybody Welcome achieves.</p>
    <h2>Where do I start?</h2>
    <p>Simply grab a cuppa, click on the link below and you’re good to go! Get ready to welcome the world…..
    Get ready to make Everybody Welcome!</p>
</div>
    <?php include("Footer.php");?>